<table width="100%" style="font-family: Calibri, Arial, sans-serif; font-size:11pt;">

    {{-- HEADER TANPA BORDER --}}
    <tr>
        <td colspan="8"
            style="text-align:center; font-size:16pt; font-weight:bold; color:#1e40af;">
            SILOG POLRES - SISTEM LOGISTIK KEPOLISIAN
        </td>
    </tr>

    <tr>
        <td colspan="8" style="text-align:center;">
            Tanggal Generate: {{ now()->format('d/m/Y H:i') }}
        </td>
    </tr>

    {{-- BARIS KOSONG --}}
    <tr>
        <td colspan="8">&nbsp;</td>
    </tr>

    {{-- JUDUL LAPORAN (BORDER MULAI DI SINI) --}}
    <tr>
        <th colspan="8"
            style="border:1px solid #000; text-align:center; font-size:14pt; font-weight:bold;">
            LAPORAN PERMINTAAN BARANG - {{ $user->name }}
        </th>
    </tr>

    <tr>
        <th colspan="8"
            style="border:1px solid #000; text-align:center;">
            Periode: {{ $filters['start_date'] ?? '-' }} s/d {{ $filters['end_date'] ?? '-' }}
        </th>
    </tr>

    {{-- HEADER TABEL --}}
    <tr style="background:#f2f2f2; text-align:center; font-weight:bold;">
        <th style="border:1px solid #000;">No</th>
        <th style="border:1px solid #000;">Kode Permintaan</th>
        <th style="border:1px solid #000;">Barang</th>
        <th style="border:1px solid #000;">Jumlah</th>
        <th style="border:1px solid #000;">Satuan</th>
        <th style="border:1px solid #000;">Satker</th>
        <th style="border:1px solid #000;">Tanggal</th>
        <th style="border:1px solid #000;">Status</th>
    </tr>

    {{-- DATA --}}
    @foreach($permintaan as $i => $p)
    <tr>
        <td style="border:1px solid #000; text-align:center;">{{ $i + 1 }}</td>
        <td style="border:1px solid #000;">{{ $p->kode_permintaan }}</td>
        <td style="border:1px solid #000;">{{ $p->barang->nama_barang ?? '-' }}</td>
        <td style="border:1px solid #000; text-align:center;">{{ $p->jumlah }}</td>
        <td style="border:1px solid #000; text-align:center;">
            {{ $p->barang->satuan->nama_satuan ?? '-' }}
        </td>
        <td style="border:1px solid #000;">{{ $p->satker->nama_satker ?? '-' }}</td>
        <td style="border:1px solid #000; text-align:center;">
            {{ $p->created_at->format('d/m/Y') }}
        </td>
        <td style="border:1px solid #000; text-align:center;">
            {{ ucfirst($p->status) }}
        </td>
    </tr>
    @endforeach

    {{-- BARIS KOSONG --}}
    <tr>
        <td colspan="8">&nbsp;</td>
    </tr>

    {{-- FOOTER TANPA BORDER --}}
    <tr>
        <td colspan="8" style="text-align:center;">
            Generated by SILOG Polres - Sistem Logistik
        </td>
    </tr>

</table>
